version: '3'

services:
  app:
    image: softvence/bertend_server:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend

  # MongoDB container
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  # One-time init container to enable replica set
  mongo-init-replica:
    image: mongodb/mongodb-community-server:latest
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
      sleep 5 &&
      mongosh --host mongo --eval 'rs.initiate()' &&
      echo '✅ MongoDB replica set initialized'
      "
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
