services:
  app:
    image: softvence/bertend_server:latest
    ports:
      - "5000:5000"
    env_file:
      - .env 
    depends_on:
      - mongo
    networks:
      - backend

  # MongoDB container
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
